baseurl: /tampabay
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: tampabay
github_org: maptime
maptime:
  chapter: MaptimeTampaBay
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
